name: "List examples to be used by e2e tests"
description: "Return JSON array with a list of examples defined"
inputs: {}

outputs:
  examples:
    description: "The json encoded array of examples defined, split by provider"
    value: ${{steps.list.outputs.examples}}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: list
      run: |
        examples="$(echo '[]' | jq .)"
        pushd examples/full
        for candidate in $(ls -1 .)
        do
          if [ -d $candidate ]
          then
            cloud_providers=()
            pushd $candidate
            for cloud in $(ls -1 .)
            do
              if [ -d $cloud ]
              then
                examples="$(echo "$examples" | jq -c --arg name "$candidate" --arg cloud "$cloud" '.[. | length] = { "name": $name, "cloud": $cloud }')"
              fi
            done
            popd
          fi
        done
        popd
        echo "examples=${examples}" >> "$GITHUB_OUTPUT"
