name: Cleanup AWS leftovers
description: Cleanup any AWS leftovers of e2e test
inputs:
  service_name:
    required: true
    description: The full name of the service for filtering purposes
  aws_role_arn:
    required: true
    description: The ARN of the AWS role to assume for AWS tests
  aws_region:
    required: true
    description: The AWS region to use for AWS tests

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
        sparse-checkout: |
          .github/actions/cleanup-aws

    - name: Configure AWS credentials
      id: aws-auth
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.aws_region }}

    - name: Cleanup ClickHouse Instances
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws_region }}
        SERVICE_NAME: ${{ inputs.service_name }}
      run: |
        ./.github/actions/cleanup-aws/cleanup.sh
