#!/bin/bash

(
  start=$(date +%s)
  echo "========== Started pre-commit git hook at $(date -R) =========="
  (make fmt)
  (make docs)
  (make build)
  exit_code=$?
  end=$(date +%s)
  echo "========== Finished pre-commit git hook with error code $exit_code at $(date -R). The duration is $((end - start)) second(-s) =========="
  exit $exit_code
)
