name: Cleanup leftovers
description: Cleanup any leftovers of e2e test
inputs:
  api_url:
    required: false
    description: Full URL of the API service to use. Defaults to the production API endpoint https://api.clickhouse.cloud/v1
    default: ""
  organization_id:
    required: true
    description: The clickhouse organization ID
  token_key:
    required: true
    description: The clickhouse token key
    type: secret
  token_secret:
    required: true
    description: The clickhouse token secret
    type: secret
  token:
    required: true
    description: The unique token assigned to this e2e run

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
      sparse-checkout: |
        .github/actions/cleanup-clickhouse/cleanup.sh

    - name: Cleanup ClickHouse Instances
      shell: bash
      env:
        API_URL: ${{ inputs.api_url }}
        ORGANIZATION_ID: ${{ inputs.organization_id }}
        TOKEN_KEY: ${{ inputs.token_key }}
        TOKEN_SECRET: ${{ inputs.token_secret }}
        SUFFIX: ${{ inputs.token }}
      run: |
        ./.github/actions/cleanup-clickhouse/cleanup.sh
