// Command docsubcategory stamps the Terraform Registry `subcategory` frontmatter
// into the docs generated by tfplugindocs, using each resource's owning service
// group as the subcategory. The group -> subcategory mapping comes from the
// ServicePackage registry (Metadata.HumanName), so the in-code grouping and the
// published Registry sidebar share a single source of truth. See HDX-4782 and
// docs/rfcs/0001.
//
// It runs after `tfplugindocs generate` (see the Makefile docs targets) and:
//   - rewrites `subcategory: ""` -> `subcategory: "<HumanName>"` in every
//     resource and data-source doc, and
//   - writes the sorted list of allowed subcategories to allowedFile, which CI
//     pins via `tfplugindocs validate --allowed-resource-subcategories-file`.
//
// Build tags must match the generator: `make docs-alpha` builds the provider
// with `-tags alpha`, so it also runs this tool with `-tags alpha` to keep the
// registry view (and thus the stamped set) in sync.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ClickHouse/terraform-provider-clickhouse/internal/service/registry"
)

const (
	emptyFrontmatter = `subcategory: ""`
	allowedFile      = "allowed-subcategories.txt"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "docsubcategory:", err)
		os.Exit(1)
	}
}

func run() error {
	// doc path -> subcategory.
	subcats := map[string]string{}
	for _, c := range registry.Components() {
		subcats[docPath(c.Kind, c.TypeName)] = c.Group.HumanName
	}

	for path, sub := range subcats {
		if err := stamp(path, sub); err != nil {
			return err
		}
	}

	// Guard against drift: any generated resource/data-source doc the registry
	// doesn't cover would keep an empty subcategory and silently fall out of a
	// group. Fail loudly instead.
	if stray, err := unstamped(); err != nil {
		return err
	} else if len(stray) > 0 {
		return fmt.Errorf("docs with no service group (not in the registry?): %s", strings.Join(stray, ", "))
	}

	// Allowed subcategories are exactly the groups that stamped a doc.
	groups := map[string]struct{}{}
	for _, sub := range subcats {
		groups[sub] = struct{}{}
	}
	names := make([]string, 0, len(groups))
	for g := range groups {
		names = append(names, g)
	}
	sort.Strings(names)
	if err := os.WriteFile(allowedFile, []byte(strings.Join(names, "\n")+"\n"), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", allowedFile, err)
	}
	return nil
}

// docPath maps a component to its generated doc (e.g. clickhouse_service ->
// docs/resources/service.md); tfplugindocs strips the provider prefix.
func docPath(kind registry.Kind, typeName string) string {
	dir := "resources"
	if kind == registry.KindDataSource {
		dir = "data-sources"
	}
	base := strings.TrimPrefix(typeName, registry.ProviderTypeName+"_")
	return filepath.Join("docs", dir, base+".md")
}

// emptyLine / stampedLine anchor the match to a whole frontmatter line
// (newline-delimited) so a `subcategory: ""` that happens to appear in a
// description body is never rewritten.
func emptyLine() string             { return "\n" + emptyFrontmatter + "\n" }
func stampedLine(sub string) string { return fmt.Sprintf("\nsubcategory: %q\n", sub) }

func stamp(path, sub string) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if strings.Contains(string(b), stampedLine(sub)) {
		return nil // idempotent: already stamped
	}
	if !strings.Contains(string(b), emptyLine()) {
		return fmt.Errorf("%s: expected %q frontmatter to stamp", path, emptyFrontmatter)
	}
	out := strings.Replace(string(b), emptyLine(), stampedLine(sub), 1)
	// path is built from in-repo registry type names under a fixed docs/ prefix, not external input.
	if err := os.WriteFile(path, []byte(out), 0o600); err != nil { //nolint:gosec // G703: path is registry-derived, not user input
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// unstamped returns any resource/data-source doc still carrying an empty
// subcategory frontmatter line after stamping.
func unstamped() ([]string, error) {
	var stray []string
	for _, kind := range []string{"resources", "data-sources"} {
		dir := filepath.Join("docs", kind)
		entries, err := os.ReadDir(dir)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read dir %s: %w", dir, err)
		}
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
				continue
			}
			p := filepath.Join(dir, e.Name())
			b, err := os.ReadFile(p)
			if err != nil {
				return nil, fmt.Errorf("read %s: %w", p, err)
			}
			if strings.Contains(string(b), emptyLine()) {
				stray = append(stray, p)
			}
		}
	}
	sort.Strings(stray)
	return stray, nil
}
