package resource

import (
	"context"
	_ "embed"
	"fmt"
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/ClickHouse/terraform-provider-clickhouse/pkg/internal/api"
	"github.com/ClickHouse/terraform-provider-clickhouse/pkg/resource/models"
)

// Ensure provider defined types fully satisfy framework interfaces
var (
	_ resource.Resource                = &ClickPipeSSHKeyResource{}
	_ resource.ResourceWithConfigure   = &ClickPipeSSHKeyResource{}
	_ resource.ResourceWithImportState = &ClickPipeSSHKeyResource{}
)

//go:embed descriptions/clickpipes_ssh_key.md
var clickPipeSSHKeyResourceDescription string

func NewClickPipeSSHKeyResource() resource.Resource {
	return &ClickPipeSSHKeyResource{}
}

// ClickPipeSSHKeyResource defines the resource implementation.
type ClickPipeSSHKeyResource struct {
	client *api.ClientImpl
}

func (r *ClickPipeSSHKeyResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_clickpipes_ssh_key"
}

func (r *ClickPipeSSHKeyResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: clickPipeSSHKeyResourceDescription,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Unique identifier for the SSH key resource",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"service_id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The ID of the ClickHouse service this SSH key resource belongs to",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Name of the SSH key resource. Unique per service and immutable; changing it forces resource replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Description of the SSH key resource. Updatable in place.",
			},
			"host": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Hostname or IP address of the SSH bastion. Immutable; changing it forces resource replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Default:             int64default.StaticInt64(22),
				MarkdownDescription: "Port of the SSH bastion. Defaults to 22. Immutable; changing it forces resource replacement.",
				Validators: []validator.Int64{
					int64validator.Between(1, 65535),
				},
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.RequiresReplace(),
				},
			},
			"username": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Username to authenticate with on the SSH bastion. Immutable; changing it forces resource replacement.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"public_key": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The OpenSSH public key generated by the server. Install this in the bastion's `authorized_keys` before validating connectivity.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Validation lifecycle status of the SSH key resource (pending, active, or failed).",
			},
			"status_message": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Human-readable detail about the current status, e.g. the reason a validation failed.",
			},
			"last_validated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Timestamp of the last connectivity validation, if any.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Timestamp when the SSH key resource was created.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Timestamp when the SSH key resource was last updated.",
			},
		},
	}
}

func (r *ClickPipeSSHKeyResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*api.ClientImpl)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *api.ClientImpl, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func applySSHKeyToModel(serviceID string, sshKey *api.SSHKey, data *models.ClickPipeSSHKeyResourceModel) {
	data.ID = types.StringValue(sshKey.ID)
	data.ServiceID = types.StringValue(serviceID)
	data.Name = types.StringValue(sshKey.Name)
	data.Description = types.StringValue(sshKey.Description)
	data.Host = types.StringValue(sshKey.Host)
	data.Username = types.StringValue(sshKey.Username)
	data.PublicKey = types.StringValue(sshKey.PublicKey)
	data.Status = types.StringValue(sshKey.Status)
	data.StatusMessage = types.StringValue(sshKey.StatusMessage)
	data.CreatedAt = types.StringValue(sshKey.CreatedAt)
	data.UpdatedAt = types.StringValue(sshKey.UpdatedAt)

	if port, err := strconv.ParseInt(sshKey.Port, 10, 64); err == nil {
		data.Port = types.Int64Value(port)
	}

	if sshKey.LastValidatedAt != nil {
		data.LastValidatedAt = types.StringValue(*sshKey.LastValidatedAt)
	} else {
		data.LastValidatedAt = types.StringNull()
	}
}

func (r *ClickPipeSSHKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data models.ClickPipeSSHKeyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	serviceID := data.ServiceID.ValueString()

	createReq := api.CreateSSHKey{
		Name:        data.Name.ValueString(),
		Description: data.Description.ValueString(),
		Host:        data.Host.ValueString(),
		Port:        strconv.FormatInt(data.Port.ValueInt64(), 10),
		Username:    data.Username.ValueString(),
	}

	tflog.Debug(ctx, "Creating ClickPipe SSH key resource", map[string]interface{}{
		"service_id": serviceID,
		"name":       createReq.Name,
	})

	sshKey, err := r.client.CreateSSHKey(ctx, serviceID, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating ClickPipe SSH key resource", err.Error())
		return
	}

	applySSHKeyToModel(serviceID, sshKey, &data)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ClickPipeSSHKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data models.ClickPipeSSHKeyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	serviceID := data.ServiceID.ValueString()
	sshKeyID := data.ID.ValueString()

	tflog.Debug(ctx, "Reading ClickPipe SSH key resource", map[string]interface{}{
		"service_id": serviceID,
		"ssh_key_id": sshKeyID,
	})

	sshKey, err := r.client.GetSSHKey(ctx, serviceID, sshKeyID)
	if err != nil {
		if api.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading ClickPipe SSH key resource", err.Error())
		return
	}

	applySSHKeyToModel(serviceID, sshKey, &data)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ClickPipeSSHKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data models.ClickPipeSSHKeyResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	serviceID := data.ServiceID.ValueString()
	sshKeyID := data.ID.ValueString()

	description := data.Description.ValueString()
	updateReq := api.UpdateSSHKey{
		Description: &description,
	}

	tflog.Debug(ctx, "Updating ClickPipe SSH key resource", map[string]interface{}{
		"service_id": serviceID,
		"ssh_key_id": sshKeyID,
	})

	sshKey, err := r.client.UpdateSSHKey(ctx, serviceID, sshKeyID, updateReq)
	if err != nil {
		resp.Diagnostics.AddError("Error updating ClickPipe SSH key resource", err.Error())
		return
	}

	applySSHKeyToModel(serviceID, sshKey, &data)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ClickPipeSSHKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data models.ClickPipeSSHKeyResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	serviceID := data.ServiceID.ValueString()
	sshKeyID := data.ID.ValueString()

	tflog.Debug(ctx, "Deleting ClickPipe SSH key resource", map[string]interface{}{
		"service_id": serviceID,
		"ssh_key_id": sshKeyID,
	})

	err := r.client.DeleteSSHKey(ctx, serviceID, sshKeyID)
	if err != nil {
		if api.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting ClickPipe SSH key resource", err.Error())
		return
	}
}

// ImportState imports a ClickPipe SSH key resource into the state.
func (r *ClickPipeSSHKeyResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, ":")

	if len(idParts) != 2 {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import identifier with format: service_id:id. Got: %q", req.ID),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("service_id"), idParts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), idParts[1])...)
}
