//go:build alpha

package resource

import (
	"context"
	_ "embed"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/ClickHouse/terraform-provider-clickhouse/pkg/internal/api"
	"github.com/ClickHouse/terraform-provider-clickhouse/pkg/resource/models"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &PostgresInstanceResource{}
	_ resource.ResourceWithConfigure   = &PostgresInstanceResource{}
	_ resource.ResourceWithImportState = &PostgresInstanceResource{}
	_ resource.ResourceWithModifyPlan  = &PostgresInstanceResource{}
)

//go:embed descriptions/postgres_instance.md
var postgresInstanceResourceDescription string

// NewPostgresInstanceResource is a helper function to simplify the provider implementation.
func NewPostgresInstanceResource() resource.Resource {
	return &PostgresInstanceResource{}
}

// PostgresInstanceResource is the resource implementation.
type PostgresInstanceResource struct {
	client api.Client
}

// Metadata returns the resource type name.
func (r *PostgresInstanceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_postgres_instance"
}

// Schema defines the schema for the resource.
func (r *PostgresInstanceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: postgresInstanceResourceDescription,
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "ID of the Postgres instance. Generated by ClickHouse Cloud.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Description: "User defined identifier for the Postgres instance.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 50),
				},
			},
			"cloud_provider": schema.StringAttribute{
				Description: "Cloud provider in which the Postgres instance is deployed.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("aws"),
				},
			},
			"region": schema.StringAttribute{
				Description: "Region within the cloud provider in which the Postgres instance is deployed.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"postgres_version": schema.StringAttribute{
				Description: "Postgres major version.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("16", "17", "18"),
				},
			},
			"size": schema.StringAttribute{
				Description: "Size of the Postgres instance (e.g. 'standard-2').",
				Required:    true,
			},
			"storage_size": schema.Int64Attribute{
				Description: "Storage size in GiB for the Postgres instance.",
				Required:    true,
				Validators: []validator.Int64{
					int64validator.AtLeast(118),
				},
			},
			"ha_type": schema.StringAttribute{
				Description: "High availability type: 'none' (0 standbys), 'async' (1 standby), or 'sync' (2 standbys).",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("none"),
				Validators: []validator.String{
					stringvalidator.OneOf("none", "async", "sync"),
				},
			},
			"pg_config": schema.MapAttribute{
				Description: "Custom Postgres configuration parameters.",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.RequiresReplace(),
				},
			},
			"pg_bouncer_config": schema.MapAttribute{
				Description: "Custom PgBouncer configuration parameters.",
				Optional:    true,
				Computed:    true,
				ElementType: types.StringType,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.RequiresReplace(),
				},
			},
			"tags": schema.MapAttribute{
				Description: "Tags to assign to the Postgres instance.",
				Optional:    true,
				ElementType: types.StringType,
			},
			"state": schema.StringAttribute{
				Description: "Current state of the Postgres instance.",
				Computed:    true,
			},
			"is_primary": schema.BoolAttribute{
				Description: "Whether this is a primary Postgres instance.",
				Computed:    true,
			},
			"hostname": schema.StringAttribute{
				Description: "Hostname of the Postgres instance.",
				Computed:    true,
			},
			"connection_string": schema.StringAttribute{
				Description: "Connection string for the Postgres instance.",
				Computed:    true,
				Sensitive:   true,
			},
			"username": schema.StringAttribute{
				Description: "Default username for the Postgres instance.",
				Computed:    true,
			},
		},
	}
}

// Configure adds the provider configured client to the resource.
func (r *PostgresInstanceResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.client = req.ProviderData.(api.Client)
}

// Create creates the resource and sets the initial Terraform state.
func (r *PostgresInstanceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Retrieve values from plan
	var plan models.PostgresInstanceResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Build API request body from plan
	createReq := api.PostgresInstanceCreate{
		Name:        plan.Name.ValueString(),
		Provider:    plan.CloudProvider.ValueString(),
		Region:      plan.Region.ValueString(),
		Size:        plan.Size.ValueString(),
		StorageSize: int(plan.StorageSize.ValueInt64()),
	}

	if !plan.PostgresVersion.IsUnknown() && !plan.PostgresVersion.IsNull() {
		createReq.PostgresVersion = plan.PostgresVersion.ValueString()
	}

	if !plan.HAType.IsUnknown() && !plan.HAType.IsNull() {
		createReq.HAType = plan.HAType.ValueString()
	}

	if !plan.PgConfig.IsUnknown() && !plan.PgConfig.IsNull() {
		pgConfigMap := make(map[string]string)
		if diag := plan.PgConfig.ElementsAs(ctx, &pgConfigMap, false); diag.HasError() {
			resp.Diagnostics.Append(diag...)
			return
		}
		createReq.PgConfig = pgConfigMap
	}

	if !plan.PgBouncerConfig.IsUnknown() && !plan.PgBouncerConfig.IsNull() {
		pgBouncerConfigMap := make(map[string]string)
		if diag := plan.PgBouncerConfig.ElementsAs(ctx, &pgBouncerConfigMap, false); diag.HasError() {
			resp.Diagnostics.Append(diag...)
			return
		}
		createReq.PgBouncerConfig = pgBouncerConfigMap
	}

	if !plan.Tags.IsUnknown() && !plan.Tags.IsNull() {
		tagsMap := make(map[string]string)
		if diag := plan.Tags.ElementsAs(ctx, &tagsMap, false); diag.HasError() {
			resp.Diagnostics.Append(diag...)
			return
		}

		tags := make([]api.Tag, 0, len(tagsMap))
		for key, value := range tagsMap {
			tags = append(tags, api.Tag{
				Key:   key,
				Value: value,
			})
		}
		createReq.Tags = tags
	}

	// Create the Postgres instance
	instance, err := r.client.CreatePostgresInstance(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating Postgres Instance",
			"Could not create Postgres instance, unexpected error: "+err.Error(),
		)
		return
	}

	// Wait for the instance to reach "running" state
	err = r.client.WaitForPostgresInstanceState(ctx, instance.ID, func(state string) bool { return state == "running" }, 300)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Waiting for Postgres Instance",
			"Could not wait for Postgres instance to reach running state, unexpected error: "+err.Error(),
		)
		return
	}

	// Populate computed fields from the API response
	plan.ID = types.StringValue(instance.ID)
	err = r.syncPostgresState(ctx, &plan)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Postgres Instance",
			"Could not read Postgres instance id "+plan.ID.ValueString()+": "+err.Error(),
		)
		return
	}

	// Set state to fully populated data
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Read refreshes the Terraform state with the latest data.
func (r *PostgresInstanceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state models.PostgresInstanceResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	instance, err := r.client.GetPostgresInstance(ctx, state.ID.ValueString())
	if api.IsNotFound(err) {
		// Resource was deleted outside Terraform
		resp.State.RemoveResource(ctx)
		return
	} else if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Postgres Instance",
			"Could not read Postgres instance id "+state.ID.ValueString()+": "+err.Error(),
		)
		return
	}

	r.syncPostgresStateFromInstance(instance, &state)

	// Set refreshed state
	diags = resp.State.Set(ctx, state)
	resp.Diagnostics.Append(diags...)
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *PostgresInstanceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Retrieve values from plan and state
	var plan, state models.PostgresInstanceResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	postgresId := state.ID.ValueString()
	update := api.PostgresInstanceUpdate{}
	hasChange := false

	if plan.Size != state.Size {
		update.Size = plan.Size.ValueString()
		hasChange = true
	}

	if plan.StorageSize != state.StorageSize {
		storageSize := int(plan.StorageSize.ValueInt64())
		update.StorageSize = &storageSize
		hasChange = true
	}

	if plan.HAType != state.HAType {
		update.HAType = plan.HAType.ValueString()
		hasChange = true
	}

	if !plan.Tags.Equal(state.Tags) {
		hasChange = true

		// Tags use FULL REPLACEMENT — send complete []Tag array
		tags := make([]api.Tag, 0)
		if !plan.Tags.IsNull() {
			tagsMap := make(map[string]string)
			if diag := plan.Tags.ElementsAs(ctx, &tagsMap, false); diag.HasError() {
				resp.Diagnostics.Append(diag...)
				return
			}

			for key, value := range tagsMap {
				tags = append(tags, api.Tag{
					Key:   key,
					Value: value,
				})
			}
		}
		update.Tags = tags
	}

	if hasChange {
		_, err := r.client.UpdatePostgresInstance(ctx, postgresId, update)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error Updating Postgres Instance",
				"Could not update Postgres instance, unexpected error: "+err.Error(),
			)
			return
		}

		// Wait for the instance to reach "running" state after update
		err = r.client.WaitForPostgresInstanceState(ctx, postgresId, func(state string) bool { return state == "running" }, 300)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error Waiting for Postgres Instance",
				"Could not wait for Postgres instance to reach running state after update, unexpected error: "+err.Error(),
			)
			return
		}
	}

	// Sync the latest state from the API
	plan.ID = state.ID
	err := r.syncPostgresState(ctx, &plan)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Postgres Instance",
			"Could not read Postgres instance id "+plan.ID.ValueString()+": "+err.Error(),
		)
		return
	}

	// Set updated state
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *PostgresInstanceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Retrieve values from state
	var state models.PostgresInstanceResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeletePostgresInstance(ctx, state.ID.ValueString())
	if api.IsNotFound(err) {
		// Already deleted
		return
	}
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Deleting Postgres Instance",
			"Could not delete Postgres instance, unexpected error: "+err.Error(),
		)
		return
	}
}

// ImportState imports an existing resource into Terraform.
func (r *PostgresInstanceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// ModifyPlan validates plan modifications before apply.
func (r *PostgresInstanceResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		// If the entire plan is null, the resource is planned for destruction.
		return
	}

	if req.State.Raw.IsNull() {
		// Creating a new resource, no validations needed.
		return
	}

	var plan, state models.PostgresInstanceResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Check that storage_size is not decreasing
	if !plan.StorageSize.IsUnknown() && !state.StorageSize.IsNull() {
		if plan.StorageSize.ValueInt64() < state.StorageSize.ValueInt64() {
			resp.Diagnostics.AddAttributeError(
				path.Root("storage_size"),
				"Invalid Update",
				"Postgres storage can only be increased, not decreased",
			)
		}
	}
}

// syncPostgresState fetches the latest Postgres instance from the API and updates the model.
func (r *PostgresInstanceResource) syncPostgresState(ctx context.Context, state *models.PostgresInstanceResourceModel) error {
	instance, err := r.client.GetPostgresInstance(ctx, state.ID.ValueString())
	if err != nil {
		return fmt.Errorf("error fetching Postgres instance: %w", err)
	}

	r.syncPostgresStateFromInstance(instance, state)
	return nil
}

// syncPostgresStateFromInstance maps an api.PostgresInstance to the Terraform state model.
func (r *PostgresInstanceResource) syncPostgresStateFromInstance(instance *api.PostgresInstance, state *models.PostgresInstanceResourceModel) {
	state.ID = types.StringValue(instance.ID)
	state.Name = types.StringValue(instance.Name)
	state.CloudProvider = types.StringValue(instance.Provider)
	state.Region = types.StringValue(instance.Region)
	state.PostgresVersion = types.StringValue(instance.PostgresVersion)
	state.Size = types.StringValue(instance.Size)
	state.StorageSize = types.Int64Value(int64(instance.StorageSize))
	state.HAType = types.StringValue(instance.HAType)
	state.State = types.StringValue(instance.State)
	state.IsPrimary = types.BoolValue(instance.IsPrimary)
	state.Hostname = types.StringValue(instance.Hostname)
	state.ConnectionString = types.StringValue(instance.ConnectionString)
	state.Username = types.StringValue(instance.Username)

	// Map pgConfig
	if instance.PgConfig == nil {
		state.PgConfig = types.MapNull(types.StringType)
	} else {
		pgConfigValues := make(map[string]attr.Value, len(instance.PgConfig))
		for k, v := range instance.PgConfig {
			pgConfigValues[k] = types.StringValue(v)
		}
		state.PgConfig, _ = types.MapValue(types.StringType, pgConfigValues)
	}

	// Map pgBouncerConfig
	if instance.PgBouncerConfig == nil {
		state.PgBouncerConfig = types.MapNull(types.StringType)
	} else {
		pgBouncerConfigValues := make(map[string]attr.Value, len(instance.PgBouncerConfig))
		for k, v := range instance.PgBouncerConfig {
			pgBouncerConfigValues[k] = types.StringValue(v)
		}
		state.PgBouncerConfig, _ = types.MapValue(types.StringType, pgBouncerConfigValues)
	}

	// Map tags
	if len(instance.Tags) == 0 {
		state.Tags = types.MapNull(types.StringType)
	} else {
		tagsValues := make(map[string]attr.Value, len(instance.Tags))
		for _, tag := range instance.Tags {
			tagsValues[tag.Key] = types.StringValue(tag.Value)
		}
		state.Tags, _ = types.MapValue(types.StringType, tagsValues)
	}
}
