resource "clickhouse_postgres_service" "example" {
  name           = "my-postgres"
  cloud_provider = "aws"
  region         = "us-east-1"
  size           = "c6gd.large"

  # High-availability mode: "none" (default), "async", or "sync".
  ha_type = "async"

  tags = {
    environment = "production"
    team        = "data"
  }

  # The password is server-generated by default. To manage it yourself, set
  # `password` (stored in sensitive state).
}
