name: Validate GoReleaser configuration

on:
  pull_request: {}

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  goreleaser-check:
    runs-on: k8s-small
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          install-only: true

      - name: Validate goreleaser configs
        run: make goreleaser-check
