name: Test import

on:
  workflow_dispatch:
    inputs:
      api_env:
        type: choice
        default: Production
        options:
          - Production
          - Staging
          - Development
          - Custom
        description: What API ENV to use as backend.
      api_url:
        type: string
        default: ""
        description: (Optional) Full URL of the API service to use when API Env is 'Custom'
      organization_id:
        type: string
        default: ""
        description: (Optional) Organization ID to use when API Env is 'Custom'
      api_key_id:
        type: string
        default: ""
        description: (Optional) API Key ID to use when API Env is 'Custom'
      api_key_secret:
        type: string
        default: ""
        description: (Optional) API Key secret to use when API Env is 'Custom'

defaults:
  run:
    shell: bash

jobs:
  # Generate a random token to tag the tests with
  token:
    outputs:
      token: ${{ steps.generate.outputs.token }}
    runs-on: k8s-nano
    steps:
      - name: Generate
        id: generate
        run: |
          token="$(date '+%s')"
          echo "token=${token}" >> $GITHUB_OUTPUT

  # Find the most recent releases of terraform CLI
  find-tf-releases:
    outputs:
      releases: ${{ steps.find.outputs.releases }}
    runs-on: k8s-nano
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find TF releases
        uses: ./.github/actions/find-tf-releases
        id: find
        with:
          count: '1'

  # Run import tests
  import:
    needs: [ "token", "find-tf-releases" ]
    runs-on: k8s-medium
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        tf_release: ${{ fromJSON(needs.find-tf-releases.outputs.releases) }}
        cloud_provider: [ "aws", "azure", "gcp" ]
        test_name : ["generic"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate service name
        uses: ./.github/actions/generate-service-name
        id: service_name
        with:
          test_type: import
          test_name: ${{ matrix.test_name }}
          tf_release: ${{ matrix.tf_release }}
          cloud_provider: ${{ matrix.cloud_provider }}
          token: ${{ needs.token.outputs.token }}

      - name: Get API details for env
        id: credentials
        env:
          api_env: "${{ inputs.api_env }}"
          api_env_production: "${{ secrets.API_ENV_PRODUCTION }}"
          api_env_staging: "${{ secrets.API_ENV_STAGING }}"
          api_env_development: "${{ secrets.API_ENV_DEVELOPMENT }}"
          api_url: "${{ inputs.api_url }}"
          organization_id: "${{ inputs.organization_id }}"
          api_key_id: "${{ inputs.api_key_id }}"
          api_key_secret: "${{ inputs.api_key_secret }}"
        run: |
          bash ./.github/scripts/set_api_env.sh ${{ matrix.cloud_provider }}

      - name: Import
        id: import
        uses: ./.github/actions/import
        with:
          api_url: ${{ steps.credentials.outputs.api_url }}
          organization_id: ${{ steps.credentials.outputs.organization_id }}
          token_key: ${{ steps.credentials.outputs.api_key_id }}
          token_secret: ${{ steps.credentials.outputs.api_key_secret }}
          service_name: ${{steps.service_name.outputs.service_name}}
          tf_release: ${{ matrix.tf_release }}
          cloud_provider: ${{ matrix.cloud_provider }}
          region: ${{ steps.credentials.outputs.region }}


  # Delete any leftover service that might have failed deleting
  cleanup:
    runs-on: k8s-small
    needs: [ "import", "token" ]
    if: always()
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get API details for env
        id: credentials
        env:
          api_env: "${{ inputs.api_env }}"
          api_env_production: "${{ secrets.API_ENV_PRODUCTION }}"
          api_env_staging: "${{ secrets.API_ENV_STAGING }}"
          api_env_development: "${{ secrets.API_ENV_DEVELOPMENT }}"
          api_url: "${{ inputs.api_url }}"
          organization_id: "${{ inputs.organization_id }}"
          api_key_id: "${{ inputs.api_key_id }}"
          api_key_secret: "${{ inputs.api_key_secret }}"
        run: |
          bash ./.github/scripts/set_api_env.sh
      - name: Cleanup ClickHouse
        uses: ./.github/actions/cleanup-clickhouse
        with:
          api_url: ${{ steps.credentials.outputs.api_url }}
          organization_id: ${{ steps.credentials.outputs.organization_id }}
          token_key: ${{ steps.credentials.outputs.api_key_id }}
          token_secret: ${{ steps.credentials.outputs.api_key_secret }}
          token: ${{needs.token.outputs.token}}
