name: Prepare for release

on:
  push:
    branches:
      - "release-automation"

defaults:
  run:
    shell: bash

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: [dataplane, self-hosted, linux, x64, small]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check release
        id: check
        run: |
          last_commit_msg="git log -1 --pretty=%B|head -n1"
          
          echo "Last commit msg = '${last_commit_msg}'"
          
          if [[ $last_commit_msg == \[RELEASE* ]]
          then
            version="$(echo "$last_commit_msg" | cut -d"]" -f1 | cut -d" " -f2)"
          else
            echo "Latest commit does not look like a release commit"
            echo "release-version=null" >> $GITHUB_OUTPUT
            exit 0
          fi
                    
          # strip any leading "v" from the release.
          version="${version#v}"
          
          # validate semver.
          if [[ $version =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
            echo "Preparing release $version"
          else
            echo "Invalid semver $version in branch name"
            exit 1
          fi
          
          echo "release-version=${version}" >> $GITHUB_OUTPUT

      - name: Create tag
        if: ${{ steps.check.outputs.release-version != 'null' }}
        run: |
          tag="disabled-v${{ steps.check.outputs.release-version }}"
          git tag $tag
          git push origin $tag
