name: Prepare for release

on:
  push:
    branches:
      - release-automation
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "The semver formatted version for the new release"

defaults:
  run:
    shell: bash

jobs:
  bump:
    permissions:
      contents: write
      pull-requests: write

    runs-on: [dataplane, self-hosted, linux, x64, small]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump provider version in examples
        id: bump
        run: |
          #version="${{ inputs.logLevel }}"
          version="0.2.2"
          
          # strip any leading "v" from the release.
          version="${version#v}"
          
          # validate semver.
          if [[ $version =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
            echo "Preparing release $version"
          else
            echo "Invalid semver $version in branch name"
            exit 1
          fi
          
          echo "release-version=${version}" >> $GITHUB_OUTPUT
          
          # Bump semver in examples
          export CLICKHOUSE_TERRAFORM_PROVIDER_VERSION="$version"
          for f in `find examples -name provider.tf.template`
          do
            dst="${f%.template}"
            cat $f | envsubst > $dst
          
            sed -i '1s/^/# This file is generated automatically please do not edit\n/' $dst
          done

      - name: Open PR with changes
        id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "bump-provider-to-${{ steps.bump.outputs.release-version }}"
          title: "[RELEASE ${{ steps.bump.outputs.release-version }}] Bump provider version in examples"
